[project]
name = "train-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "catboost>=1.2.7",
    "lightgbm>=4.5.0",
    "onnxmltools>=1.13.0",
    "scikit-learn>=1.6.1",
]
